<#
============================================================
 TunnelKeeper - Modern Graphical Dashboard
 Native Windows WPF GUI for Minecraft Dynamic Gateway
============================================================
#>

[CmdletBinding()]
param()

Add-Type -AssemblyName PresentationFramework, PresentationCore, WindowsBase, System.Windows.Forms, System.Drawing

$app = [System.Windows.Application]::Current
if ($null -eq $app) { $app = New-Object System.Windows.Application }
$app.ShutdownMode = [System.Windows.ShutdownMode]::OnExplicitShutdown

# ------------------------------------------------------------
# PATHS & CONFIG
# ------------------------------------------------------------
$ScriptRoot  = $PSScriptRoot
if (-not $ScriptRoot) { $ScriptRoot = Split-Path -Parent -Path $MyInvocation.MyCommand.Definition }
if (-not $ScriptRoot) { $ScriptRoot = Get-Location }

$CoreScriptPath = Join-Path $ScriptRoot "minecraft-tunnel-autostart.ps1"
$EnvFilePath    = Join-Path $ScriptRoot ".env"
$IconFilePath   = Join-Path $ScriptRoot "TunnelKeeper.ico"
$LogDir         = Join-Path $env:USERPROFILE "TunnelKeeper_Logs"

function Get-PlayerAddress {
    param([string]$Srv, [string]$Domain)
    if ([string]::IsNullOrWhiteSpace($Domain) -or $Domain -in @("yourdomain.com", "example.com")) {
        return "Configure domain in Settings"
    }
    if ($Srv -match '^_[^.]+\._[^.]+\.(.+)$') {
        $sub = $matches[1].TrimEnd('.')
        if (-not [string]::IsNullOrWhiteSpace($sub)) {
            return "$sub.$Domain"
        }
    }
    return $Domain
}

# Load settings from .env
function Load-EnvSettings {
    $cfg = @{
        DnsProvider        = "Hostinger"
        HostingerToken     = ""
        CloudflareApiToken = ""
        CloudflareZoneId   = ""
        RootDomain         = ""
        SrvRecordName      = "_minecraft._tcp.play"
        LocalPort          = "25565"
        HotSwapMinute      = "55"
        TTL                = "60"
        Priority           = "0"
        Weight             = "5"
        LogRetentionDays   = "14"
    }
    if (Test-Path $EnvFilePath) {
        foreach ($line in Get-Content $EnvFilePath) {
            $trimmed = $line.Trim()
            if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) { continue }
            if ($trimmed -match '^([^=]+)=(.*)$') {
                $k = $matches[1].Trim()
                $v = $matches[2].Trim()
                if ($v -match '^["''](.*)["'']$') { $v = $matches[1] }
                if ($cfg.ContainsKey($k)) { $cfg[$k] = $v }
                if ($k -eq "CloudflareToken") { $cfg["CloudflareApiToken"] = $v }
            }
        }
    }
    return $cfg
}

function Save-EnvSettings {
    param($cfg)
    $lines = @(
        "# ============================================================",
        "# TunnelKeeper Gateway - Environment Configuration",
        "# Auto-generated by TunnelKeeper GUI",
        "# ============================================================",
        "",
        "DnsProvider=$($cfg.DnsProvider)",
        "",
        "# ---- Hostinger Configuration ----",
        "HostingerToken=$($cfg.HostingerToken)",
        "",
        "# ---- Cloudflare Configuration ----",
        "CloudflareApiToken=$($cfg.CloudflareApiToken)",
        "CloudflareZoneId=$($cfg.CloudflareZoneId)",
        "",
        "# ---- Domain & Tunnel Settings ----",
        "RootDomain=$($cfg.RootDomain)",
        "SrvRecordName=$($cfg.SrvRecordName)",
        "LocalPort=$($cfg.LocalPort)",
        "HotSwapMinute=$($cfg.HotSwapMinute)",
        "TTL=$($cfg.TTL)",
        "Priority=$($cfg.Priority)",
        "Weight=$($cfg.Weight)",
        "LogRetentionDays=$($cfg.LogRetentionDays)"
    )
    Set-Content -Path $EnvFilePath -Value $lines -Encoding UTF8
}

function Get-CurrentLogFile {
    return Join-Path $LogDir ("gateway_$(Get-Date -Format 'yyyy-MM-dd').log")
}

# ------------------------------------------------------------
# MODERN DARK THEME XAML
# ------------------------------------------------------------
$xaml = @"
<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="TunnelKeeper - Minecraft Gateway"
        Height="720" Width="880"
        MinHeight="600" MinWidth="750"
        WindowStartupLocation="CenterScreen"
        Background="#0F172A"
        FontFamily="Segoe UI Variable Display, Segoe UI, sans-serif"
        Foreground="#F8FAFC">
    <Window.Resources>
        <!-- Modern ScrollViewer Style -->
        <Style TargetType="{x:Type TextBox}">
            <Setter Property="Background" Value="#0B132B"/>
            <Setter Property="Foreground" Value="#F8FAFC"/>
            <Setter Property="BorderBrush" Value="#334155"/>
            <Setter Property="BorderThickness" Value="1"/>
            <Setter Property="Padding" Value="10,8"/>
            <Setter Property="FontSize" Value="13"/>
        </Style>
        <Style TargetType="{x:Type PasswordBox}">
            <Setter Property="Background" Value="#0B132B"/>
            <Setter Property="Foreground" Value="#F8FAFC"/>
            <Setter Property="BorderBrush" Value="#334155"/>
            <Setter Property="BorderThickness" Value="1"/>
            <Setter Property="Padding" Value="10,8"/>
            <Setter Property="FontSize" Value="13"/>
        </Style>
    </Window.Resources>

    <Grid Margin="24">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/> <!-- Header -->
            <RowDefinition Height="Auto"/> <!-- Tab Bar -->
            <RowDefinition Height="*"/>    <!-- Tab Content -->
        </Grid.RowDefinitions>

        <!-- HEADER -->
        <Grid Grid.Row="0" Margin="0,0,0,20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="*"/>
                <ColumnDefinition Width="Auto"/>
            </Grid.ColumnDefinitions>

            <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                <Border Width="44" Height="44" CornerRadius="12" Background="#0284C7" Margin="0,0,14,0">
                    <TextBlock Text="TK" FontWeight="Bold" FontSize="20" Foreground="White"
                               HorizontalAlignment="Center" VerticalAlignment="Center"/>
                </Border>
                <StackPanel VerticalAlignment="Center">
                    <TextBlock Text="TunnelKeeper" FontSize="22" FontWeight="Bold" Foreground="#F8FAFC"/>
                    <TextBlock Text="Dynamic Minecraft TCP Tunnel &amp; DNS Hot-Swap Gateway" FontSize="12" Foreground="#94A3B8"/>
                </StackPanel>
            </StackPanel>

            <!-- Header Quick Action Buttons -->
            <StackPanel Grid.Column="1" Orientation="Horizontal" VerticalAlignment="Center">
                <Button Name="BtnMinimizeTray" Content="Minimize to Tray"
                        Background="#1E293B" Foreground="#94A3B8" BorderBrush="#334155" BorderThickness="1"
                        Padding="12,6" FontSize="12" Cursor="Hand" Margin="0,0,10,0"/>
            </StackPanel>
        </Grid>

        <!-- NAVIGATION TABS -->
        <Border Grid.Row="1" Background="#1E293B" CornerRadius="10" Padding="4" Margin="0,0,0,20" BorderBrush="#334155" BorderThickness="1">
            <Grid>
                <Grid.ColumnDefinitions>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="*"/>
                    <ColumnDefinition Width="*"/>
                </Grid.ColumnDefinitions>

                <Button Name="NavTabDashboard" Grid.Column="0" Content="Dashboard"
                        Background="#0284C7" Foreground="#FFFFFF" FontWeight="SemiBold"
                        Padding="0,10" BorderThickness="0" Cursor="Hand"/>
                <Button Name="NavTabSettings" Grid.Column="1" Content="Settings"
                        Background="Transparent" Foreground="#94A3B8" FontWeight="SemiBold"
                        Padding="0,10" BorderThickness="0" Cursor="Hand"/>
                <Button Name="NavTabLogs" Grid.Column="2" Content="Live Logs"
                        Background="Transparent" Foreground="#94A3B8" FontWeight="SemiBold"
                        Padding="0,10" BorderThickness="0" Cursor="Hand"/>
            </Grid>
        </Border>

        <!-- CONTENT PANELS -->
        <Grid Grid.Row="2">

            <!-- ================= PAGE 1: DASHBOARD ================= -->
            <Grid Name="PanelDashboard" Visibility="Visible">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/> <!-- Status Cards -->
                    <RowDefinition Height="Auto"/> <!-- Action Controls -->
                    <RowDefinition Height="*"/>    <!-- Activity Stream -->
                </Grid.RowDefinitions>

                <!-- TOP STATUS CARDS -->
                <Grid Grid.Row="0" Margin="0,0,0,20">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="16"/>
                        <ColumnDefinition Width="1.3*"/>
                        <ColumnDefinition Width="16"/>
                        <ColumnDefinition Width="*"/>
                    </Grid.ColumnDefinitions>

                    <!-- Card 1: Service State -->
                    <Border Grid.Column="0" Background="#1E293B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="16">
                        <StackPanel>
                            <TextBlock Text="SERVICE STATE" FontSize="11" FontWeight="SemiBold" Foreground="#94A3B8" Margin="0,0,0,8"/>
                            <Border Name="BadgeStatus" Background="#450A0A" CornerRadius="8" Padding="10,6" Margin="0,0,0,10" HorizontalAlignment="Left">
                                <TextBlock Name="TxtBadgeStatus" Text="STOPPED" FontWeight="Bold" FontSize="12" Foreground="#F87171"/>
                            </Border>
                            <TextBlock Name="TxtProviderLabel" Text="Provider: Hostinger" FontSize="12" Foreground="#CBD5E1" Margin="0,0,0,4"/>
                            <TextBlock Name="TxtLocalServerLabel" Text="Minecraft: Checking..." FontSize="12" Foreground="#94A3B8"/>
                        </StackPanel>
                    </Border>

                    <!-- Card 2: Public Domain -->
                    <Border Grid.Column="2" Background="#1E293B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="16">
                        <StackPanel>
                            <TextBlock Text="PUBLIC SERVER ADDRESS" FontSize="11" FontWeight="SemiBold" Foreground="#94A3B8" Margin="0,0,0,6"/>
                            <TextBlock Name="TxtPublicDomain" Text="Configure domain in Settings" FontSize="17" FontWeight="Bold" Foreground="#38BDF8" Margin="0,0,0,4"/>
                            <TextBlock Name="TxtLiveEndpoint" Text="SRV: Resolving live address..." FontSize="11" Foreground="#94A3B8" Margin="0,0,0,10" TextTrimming="CharacterEllipsis"/>
                            <Button Name="BtnCopyDomain" Content="Copy Server Address"
                                    Background="#0284C7" Foreground="White" FontWeight="SemiBold"
                                    Padding="12,6" FontSize="12" BorderThickness="0" Cursor="Hand" HorizontalAlignment="Left"/>
                        </StackPanel>
                    </Border>

                    <!-- Card 3: Rotation & Cycles -->
                    <Border Grid.Column="4" Background="#1E293B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="16">
                        <StackPanel>
                            <TextBlock Text="HOT-SWAP ROTATION" FontSize="11" FontWeight="SemiBold" Foreground="#94A3B8" Margin="0,0,0,8"/>
                            <TextBlock Name="TxtSwapInfo" Text="Interval: ~55 min" FontSize="13" FontWeight="SemiBold" Foreground="#F8FAFC" Margin="0,0,0,4"/>
                            <TextBlock Name="TxtCycleCount" Text="Cycles: 0 swaps" FontSize="12" Foreground="#CBD5E1" Margin="0,0,0,4"/>
                            <TextBlock Name="TxtUptime" Text="Uptime: Idle" FontSize="12" Foreground="#94A3B8"/>
                        </StackPanel>
                    </Border>
                </Grid>

                <!-- ACTION BUTTONS -->
                <Grid Grid.Row="1" Margin="0,0,0,20">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="*"/>
                        <ColumnDefinition Width="16"/>
                        <ColumnDefinition Width="Auto"/>
                    </Grid.ColumnDefinitions>

                    <Button Name="BtnToggleService" Grid.Column="0" Content="Start Tunnel Gateway"
                            Height="50" Background="#059669" Foreground="White" FontSize="16" FontWeight="Bold"
                            BorderThickness="0" Cursor="Hand"/>

                    <Button Name="BtnRestartService" Grid.Column="2" Content="Force Restart"
                            Height="50" Background="#334155" Foreground="White" FontSize="14" FontWeight="SemiBold"
                            Padding="20,0" BorderThickness="0" Cursor="Hand"/>
                </Grid>

                <!-- LIVE ACTIVITY STREAM (Mini Console) -->
                <Border Grid.Row="2" Background="#0B132B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="14">
                    <Grid>
                        <Grid.RowDefinitions>
                            <RowDefinition Height="Auto"/>
                            <RowDefinition Height="*"/>
                        </Grid.RowDefinitions>

                        <Grid Grid.Row="0" Margin="0,0,0,10">
                            <TextBlock Text="LIVE ACTIVITY" FontSize="11" FontWeight="SemiBold" Foreground="#94A3B8"/>
                            <TextBlock Name="TxtLogFileSummary" Text="" FontSize="11" Foreground="#64748B" HorizontalAlignment="Right"/>
                        </Grid>

                        <TextBox Name="TxtDashboardLogs" Grid.Row="1"
                                 Background="Transparent" Foreground="#E2E8F0" BorderThickness="0"
                                 FontFamily="Consolas, monospace" FontSize="12"
                                 IsReadOnly="True" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"/>
                    </Grid>
                </Border>
            </Grid>

            <!-- ================= PAGE 2: SETTINGS ================= -->
            <ScrollViewer Name="PanelSettings" Visibility="Collapsed" VerticalScrollBarVisibility="Auto">
                <StackPanel Margin="0,0,12,0">

                    <!-- Notification Banner -->
                    <Border Name="SettingsNoticeBanner" Background="#064E3B" CornerRadius="8" Padding="14,10" Margin="0,0,0,18" Visibility="Collapsed">
                        <TextBlock Name="TxtSettingsNotice" Text="Settings saved successfully to .env!" Foreground="#34D399" FontSize="13" FontWeight="SemiBold"/>
                    </Border>

                    <!-- CARD 1: DNS Provider Selection -->
                    <Border Background="#1E293B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="18" Margin="0,0,0,18">
                        <StackPanel>
                            <TextBlock Text="DNS Provider" FontSize="16" FontWeight="Bold" Foreground="#F8FAFC" Margin="0,0,0,4"/>
                            <TextBlock Text="Select which provider manages your Minecraft server domain." FontSize="12" Foreground="#94A3B8" Margin="0,0,0,14"/>

                            <StackPanel Orientation="Horizontal" Margin="0,0,0,16">
                                <RadioButton Name="RadioHostinger" Content="Hostinger" GroupName="ProviderGroup"
                                             Foreground="White" FontSize="14" FontWeight="SemiBold" IsChecked="True" Margin="0,0,32,0"/>
                                <RadioButton Name="RadioCloudflare" Content="Cloudflare" GroupName="ProviderGroup"
                                             Foreground="White" FontSize="14" FontWeight="SemiBold"/>
                            </StackPanel>

                            <!-- Hostinger Settings Block -->
                            <StackPanel Name="BlockHostinger">
                                <TextBlock Text="Hostinger API Token *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                <Grid Margin="0,0,0,6">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="*"/>
                                        <ColumnDefinition Width="Auto"/>
                                    </Grid.ColumnDefinitions>
                                    <PasswordBox Name="TxtHostingerToken" Grid.Column="0" Margin="0,0,8,0"/>
                                    <TextBox Name="TxtHostingerTokenVisible" Grid.Column="0" Margin="0,0,8,0" Visibility="Collapsed"/>
                                    <Button Name="BtnToggleHostingerToken" Grid.Column="1" Content="Show"
                                            Background="#334155" Foreground="White" Padding="14,6" FontSize="12" Cursor="Hand" BorderThickness="0"/>
                                </Grid>
                                <TextBlock Text="Requires DNS management permissions. Get it from Hostinger Dashboard > Profile > API" FontSize="11" Foreground="#64748B"/>
                            </StackPanel>

                            <!-- Cloudflare Settings Block -->
                            <StackPanel Name="BlockCloudflare" Visibility="Collapsed">
                                <TextBlock Text="Cloudflare API Token *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                <Grid Margin="0,0,0,6">
                                    <Grid.ColumnDefinitions>
                                        <ColumnDefinition Width="*"/>
                                        <ColumnDefinition Width="Auto"/>
                                    </Grid.ColumnDefinitions>
                                    <PasswordBox Name="TxtCloudflareToken" Grid.Column="0" Margin="0,0,8,0"/>
                                    <TextBox Name="TxtCloudflareTokenVisible" Grid.Column="0" Margin="0,0,8,0" Visibility="Collapsed"/>
                                    <Button Name="BtnToggleCloudflareToken" Grid.Column="1" Content="Show"
                                            Background="#334155" Foreground="White" Padding="14,6" FontSize="12" Cursor="Hand" BorderThickness="0"/>
                                </Grid>
                                <TextBlock Text="Requires Zone.DNS Edit permissions. Get it from Cloudflare Dashboard > Profile > API Tokens" FontSize="11" Foreground="#64748B" Margin="0,0,0,12"/>

                                <TextBlock Text="Cloudflare Zone ID (Optional)" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                <TextBox Name="TxtCloudflareZoneId" Margin="0,0,0,6"/>
                                <TextBlock Text="Leave blank to automatically discover the Zone ID using your Root Domain." FontSize="11" Foreground="#64748B"/>
                            </StackPanel>
                        </StackPanel>
                    </Border>

                    <!-- CARD 2: Domain & Network Settings -->
                    <Border Background="#1E293B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="18" Margin="0,0,0,18">
                        <StackPanel>
                            <TextBlock Text="Domain &amp; Port Settings" FontSize="16" FontWeight="Bold" Foreground="#F8FAFC" Margin="0,0,0,4"/>
                            <TextBlock Text="Configure your domain zone and Minecraft local server port." FontSize="12" Foreground="#94A3B8" Margin="0,0,0,14"/>

                            <Grid Margin="0,0,0,14">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="16"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <StackPanel Grid.Column="0">
                                    <TextBlock Text="Root Domain *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtRootDomain" Text=""/>
                                    <TextBlock Text="e.g. yourdomain.com (Required)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>

                                <StackPanel Grid.Column="2">
                                    <TextBlock Text="SRV Record Name *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtSrvRecordName" Text="_minecraft._tcp.play"/>
                                    <TextBlock Text="e.g. _minecraft._tcp.play (Required)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>
                            </Grid>

                            <Grid Margin="0,0,0,14">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="16"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <StackPanel Grid.Column="0">
                                    <TextBlock Text="Local Minecraft Port *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtLocalPort" Text="25565"/>
                                    <TextBlock Text="Port your local server listens on (default: 25565)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>

                                <StackPanel Grid.Column="2">
                                    <TextBlock Text="Hot-Swap Interval (Minutes) *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtHotSwapMinute" Text="55"/>
                                    <TextBlock Text="Pre-starts next tunnel before 60-min Pinggy limit (default: 55)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>
                            </Grid>

                            <Grid Margin="0,0,0,14">
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="16"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <StackPanel Grid.Column="0">
                                    <TextBlock Text="SRV Priority *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtPriority" Text="0"/>
                                    <TextBlock Text="Priority of the SRV record (0-65535, default: 0)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>

                                <StackPanel Grid.Column="2">
                                    <TextBlock Text="SRV Weight *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtWeight" Text="5"/>
                                    <TextBlock Text="Weight of the SRV record (0-65535, default: 5)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>
                            </Grid>

                            <Grid>
                                <Grid.ColumnDefinitions>
                                    <ColumnDefinition Width="*"/>
                                    <ColumnDefinition Width="16"/>
                                    <ColumnDefinition Width="*"/>
                                </Grid.ColumnDefinitions>

                                <StackPanel Grid.Column="0">
                                    <TextBlock Text="DNS TTL (Seconds) *" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtTTL" Text="60"/>
                                    <TextBlock Text="Time-To-Live in seconds for fast updates (default: 60)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>

                                <StackPanel Grid.Column="2">
                                    <TextBlock Text="Log Retention (Days)" FontSize="13" FontWeight="SemiBold" Foreground="#CBD5E1" Margin="0,0,0,6"/>
                                    <TextBox Name="TxtLogRetention" Text="14"/>
                                    <TextBlock Text="Auto-purges old logs on startup (default: 14)" FontSize="11" Foreground="#64748B" Margin="0,4,0,0"/>
                                </StackPanel>
                            </Grid>
                        </StackPanel>
                    </Border>

                    <!-- SAVE BUTTON -->
                    <Button Name="BtnSaveSettings" Content="Save Settings to .env"
                            Height="46" Background="#0284C7" Foreground="White" FontSize="15" FontWeight="Bold"
                            BorderThickness="0" Cursor="Hand" Margin="0,0,0,24"/>
                </StackPanel>
            </ScrollViewer>

            <!-- ================= PAGE 3: FULL LIVE LOGS ================= -->
            <Grid Name="PanelLogs" Visibility="Collapsed">
                <Grid.RowDefinitions>
                    <RowDefinition Height="Auto"/>
                    <RowDefinition Height="*"/>
                </Grid.RowDefinitions>

                <Grid Grid.Row="0" Margin="0,0,0,12">
                    <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                        <CheckBox Name="ChkAutoScroll" Content="Auto-scroll to bottom" Foreground="#94A3B8" IsChecked="True" VerticalAlignment="Center" Margin="0,0,16,0"/>
                        <Button Name="BtnClearLogView" Content="Clear View" Background="#1E293B" Foreground="#94A3B8" BorderBrush="#334155" BorderThickness="1" Padding="10,4" FontSize="11" Cursor="Hand" Margin="0,0,8,0"/>
                        <Button Name="BtnOpenLogFile" Content="Open in Notepad" Background="#1E293B" Foreground="#94A3B8" BorderBrush="#334155" BorderThickness="1" Padding="10,4" FontSize="11" Cursor="Hand" Margin="0,0,8,0"/>
                        <Button Name="BtnOpenLogFolder" Content="Open Logs Folder" Background="#1E293B" Foreground="#94A3B8" BorderBrush="#334155" BorderThickness="1" Padding="10,4" FontSize="11" Cursor="Hand"/>
                    </StackPanel>
                    <TextBlock Name="TxtFullLogPath" Text="" FontSize="11" Foreground="#64748B" VerticalAlignment="Center" HorizontalAlignment="Right"/>
                </Grid>

                <Border Grid.Row="1" Background="#0B132B" CornerRadius="12" BorderBrush="#334155" BorderThickness="1" Padding="12">
                    <TextBox Name="TxtFullLogs"
                             Background="Transparent" Foreground="#E2E8F0" BorderThickness="0"
                             FontFamily="Consolas, monospace" FontSize="12"
                             IsReadOnly="True" TextWrapping="Wrap" VerticalScrollBarVisibility="Auto"/>
                </Border>
            </Grid>
        </Grid>
    </Grid>
</Window>
"@

# ------------------------------------------------------------
# LOAD XAML & BIND CONTROLS
# ------------------------------------------------------------
$reader = [System.Xml.XmlReader]::Create([System.IO.StringReader]::new($xaml))
$window = [System.Windows.Markup.XamlReader]::Load($reader)

# Tab Navigation Controls
$NavTabDashboard = $window.FindName("NavTabDashboard")
$NavTabSettings  = $window.FindName("NavTabSettings")
$NavTabLogs      = $window.FindName("NavTabLogs")

$PanelDashboard  = $window.FindName("PanelDashboard")
$PanelSettings   = $window.FindName("PanelSettings")
$PanelLogs       = $window.FindName("PanelLogs")

# Dashboard Controls
$BadgeStatus           = $window.FindName("BadgeStatus")
$TxtBadgeStatus        = $window.FindName("TxtBadgeStatus")
$TxtProviderLabel      = $window.FindName("TxtProviderLabel")
$TxtLocalServerLabel   = $window.FindName("TxtLocalServerLabel")
$TxtPublicDomain       = $window.FindName("TxtPublicDomain")
$TxtLiveEndpoint       = $window.FindName("TxtLiveEndpoint")
$BtnCopyDomain         = $window.FindName("BtnCopyDomain")
$TxtSwapInfo           = $window.FindName("TxtSwapInfo")
$TxtCycleCount         = $window.FindName("TxtCycleCount")
$TxtUptime             = $window.FindName("TxtUptime")
$BtnToggleService      = $window.FindName("BtnToggleService")
$BtnRestartService     = $window.FindName("BtnRestartService")
$TxtDashboardLogs      = $window.FindName("TxtDashboardLogs")
$TxtLogFileSummary     = $window.FindName("TxtLogFileSummary")
$BtnMinimizeTray       = $window.FindName("BtnMinimizeTray")

# Settings Controls
$SettingsNoticeBanner      = $window.FindName("SettingsNoticeBanner")
$TxtSettingsNotice         = $window.FindName("TxtSettingsNotice")
$RadioHostinger            = $window.FindName("RadioHostinger")
$RadioCloudflare           = $window.FindName("RadioCloudflare")
$BlockHostinger            = $window.FindName("BlockHostinger")
$BlockCloudflare           = $window.FindName("BlockCloudflare")
$TxtHostingerToken         = $window.FindName("TxtHostingerToken")
$TxtHostingerTokenVisible  = $window.FindName("TxtHostingerTokenVisible")
$BtnToggleHostingerToken   = $window.FindName("BtnToggleHostingerToken")
$TxtCloudflareToken        = $window.FindName("TxtCloudflareToken")
$TxtCloudflareTokenVisible = $window.FindName("TxtCloudflareTokenVisible")
$BtnToggleCloudflareToken  = $window.FindName("BtnToggleCloudflareToken")
$TxtCloudflareZoneId       = $window.FindName("TxtCloudflareZoneId")
$TxtRootDomain             = $window.FindName("TxtRootDomain")
$TxtSrvRecordName          = $window.FindName("TxtSrvRecordName")
$TxtLocalPort              = $window.FindName("TxtLocalPort")
$TxtHotSwapMinute          = $window.FindName("TxtHotSwapMinute")
$TxtPriority               = $window.FindName("TxtPriority")
$TxtWeight                 = $window.FindName("TxtWeight")
$TxtTTL                    = $window.FindName("TxtTTL")
$TxtLogRetention           = $window.FindName("TxtLogRetention")
$BtnSaveSettings           = $window.FindName("BtnSaveSettings")

# Live Logs Controls
$ChkAutoScroll    = $window.FindName("ChkAutoScroll")
$BtnClearLogView  = $window.FindName("BtnClearLogView")
$BtnOpenLogFile   = $window.FindName("BtnOpenLogFile")
$BtnOpenLogFolder = $window.FindName("BtnOpenLogFolder")
$TxtFullLogPath   = $window.FindName("TxtFullLogPath")
$TxtFullLogs      = $window.FindName("TxtFullLogs")

# Set Window Icon if exists
if (Test-Path $IconFilePath) {
    try {
        $window.Icon = [System.Windows.Media.Imaging.BitmapFrame]::Create([System.Uri]::new($IconFilePath))
    } catch {}
}

# ------------------------------------------------------------
# POPULATE SETTINGS FROM .ENV
# ------------------------------------------------------------
$envConfig = Load-EnvSettings

if ($envConfig.DnsProvider -match "cloudflare") {
    $RadioCloudflare.IsChecked = $true
    $BlockCloudflare.Visibility = "Visible"
    $BlockHostinger.Visibility  = "Collapsed"
} else {
    $RadioHostinger.IsChecked  = $true
    $BlockHostinger.Visibility = "Visible"
    $BlockCloudflare.Visibility = "Collapsed"
}

$TxtHostingerToken.Password        = $envConfig.HostingerToken
$TxtHostingerTokenVisible.Text     = $envConfig.HostingerToken
$TxtCloudflareToken.Password       = $envConfig.CloudflareApiToken
$TxtCloudflareTokenVisible.Text    = $envConfig.CloudflareApiToken
$TxtCloudflareZoneId.Text          = $envConfig.CloudflareZoneId
$TxtRootDomain.Text                = $envConfig.RootDomain
$TxtSrvRecordName.Text             = $envConfig.SrvRecordName
$TxtLocalPort.Text                 = $envConfig.LocalPort
$TxtHotSwapMinute.Text             = $envConfig.HotSwapMinute
$TxtPriority.Text                  = $envConfig.Priority
$TxtWeight.Text                    = $envConfig.Weight
$TxtTTL.Text                       = $envConfig.TTL
$TxtLogRetention.Text              = $envConfig.LogRetentionDays

$TxtPublicDomain.Text = Get-PlayerAddress -Srv $envConfig.SrvRecordName -Domain $envConfig.RootDomain

# ------------------------------------------------------------
# TAB SWITCHING
# ------------------------------------------------------------
function Set-ActiveTab {
    param([string]$tabName)
    $PanelDashboard.Visibility = "Collapsed"
    $PanelSettings.Visibility  = "Collapsed"
    $PanelLogs.Visibility      = "Collapsed"

    $NavTabDashboard.Background = "Transparent"
    $NavTabDashboard.Foreground = "#94A3B8"
    $NavTabSettings.Background  = "Transparent"
    $NavTabSettings.Foreground  = "#94A3B8"
    $NavTabLogs.Background      = "Transparent"
    $NavTabLogs.Foreground      = "#94A3B8"

    switch ($tabName) {
        "Dashboard" {
            $PanelDashboard.Visibility  = "Visible"
            $NavTabDashboard.Background = "#0284C7"
            $NavTabDashboard.Foreground = "#FFFFFF"
        }
        "Settings" {
            $PanelSettings.Visibility  = "Visible"
            $NavTabSettings.Background = "#0284C7"
            $NavTabSettings.Foreground = "#FFFFFF"
        }
        "Logs" {
            $PanelLogs.Visibility  = "Visible"
            $NavTabLogs.Background = "#0284C7"
            $NavTabLogs.Foreground = "#FFFFFF"
        }
    }
}

$NavTabDashboard.Add_Click({ Set-ActiveTab "Dashboard" })
$NavTabSettings.Add_Click({ Set-ActiveTab "Settings" })
$NavTabLogs.Add_Click({ Set-ActiveTab "Logs" })

# Provider radio toggles
$RadioHostinger.Add_Checked({
    $BlockHostinger.Visibility  = "Visible"
    $BlockCloudflare.Visibility = "Collapsed"
})
$RadioCloudflare.Add_Checked({
    $BlockCloudflare.Visibility = "Visible"
    $BlockHostinger.Visibility  = "Collapsed"
})

# Show/Hide Password toggles
$BtnToggleHostingerToken.Add_Click({
    if ($TxtHostingerTokenVisible.Visibility -eq "Visible") {
        $TxtHostingerToken.Password = $TxtHostingerTokenVisible.Text
        $TxtHostingerTokenVisible.Visibility = "Collapsed"
        $TxtHostingerToken.Visibility = "Visible"
        $BtnToggleHostingerToken.Content = "Show"
    } else {
        $TxtHostingerTokenVisible.Text = $TxtHostingerToken.Password
        $TxtHostingerToken.Visibility = "Collapsed"
        $TxtHostingerTokenVisible.Visibility = "Visible"
        $BtnToggleHostingerToken.Content = "Hide"
    }
})

$BtnToggleCloudflareToken.Add_Click({
    if ($TxtCloudflareTokenVisible.Visibility -eq "Visible") {
        $TxtCloudflareToken.Password = $TxtCloudflareTokenVisible.Text
        $TxtCloudflareTokenVisible.Visibility = "Collapsed"
        $TxtCloudflareToken.Visibility = "Visible"
        $BtnToggleCloudflareToken.Content = "Show"
    } else {
        $TxtCloudflareTokenVisible.Text = $TxtCloudflareToken.Password
        $TxtCloudflareToken.Visibility = "Collapsed"
        $TxtCloudflareTokenVisible.Visibility = "Visible"
        $BtnToggleCloudflareToken.Content = "Hide"
    }
})

# ------------------------------------------------------------
function Show-SettingsNotice {
    param(
        [string]$Message,
        [string]$Type = "Success"
    )
    $SettingsNoticeBanner.Visibility = "Visible"
    $TxtSettingsNotice.Text = $Message
    if ($Type -eq "Error") {
        $SettingsNoticeBanner.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#7F1D1D")
        $TxtSettingsNotice.Foreground    = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#F87171")
    } else {
        $SettingsNoticeBanner.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#064E3B")
        $TxtSettingsNotice.Foreground    = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#34D399")
    }

    $timerNotice = New-Object System.Windows.Threading.DispatcherTimer
    $timerNotice.Interval = [TimeSpan]::FromSeconds(5)
    $timerNotice.Add_Tick({
        $SettingsNoticeBanner.Visibility = "Collapsed"
        $timerNotice.Stop()
    })
    $timerNotice.Start()
}

$BtnSaveSettings.Add_Click({
    $p = if ($RadioCloudflare.IsChecked) { "Cloudflare" } else { "Hostinger" }
    $hToken = if ($TxtHostingerTokenVisible.Visibility -eq "Visible") { $TxtHostingerTokenVisible.Text.Trim() } else { $TxtHostingerToken.Password.Trim() }
    $cToken = if ($TxtCloudflareTokenVisible.Visibility -eq "Visible") { $TxtCloudflareTokenVisible.Text.Trim() } else { $TxtCloudflareToken.Password.Trim() }

    # Input validation
    if ($p -eq "Hostinger" -and [string]::IsNullOrWhiteSpace($hToken)) {
        Show-SettingsNotice "Hostinger API Token cannot be empty." "Error"
        return
    }
    if ($p -eq "Cloudflare" -and [string]::IsNullOrWhiteSpace($cToken)) {
        Show-SettingsNotice "Cloudflare API Token cannot be empty." "Error"
        return
    }

    $domain = $TxtRootDomain.Text.Trim()
    if ([string]::IsNullOrWhiteSpace($domain) -or $domain -in @("yourdomain.com", "example.com")) {
        Show-SettingsNotice "Please enter your own valid Root Domain (e.g. yourdomain.com)." "Error"
        return
    }

    $srvName = $TxtSrvRecordName.Text.Trim()
    if ([string]::IsNullOrWhiteSpace($srvName)) {
        Show-SettingsNotice "SRV Record Name cannot be empty (e.g. _minecraft._tcp.play)." "Error"
        return
    }

    $port = 0
    if (-not [int]::TryParse($TxtLocalPort.Text.Trim(), [ref]$port) -or $port -lt 1 -or $port -gt 65535) {
        Show-SettingsNotice "Local Port must be a valid port number (1 - 65535)." "Error"
        return
    }

    $swapMin = 0
    if (-not [int]::TryParse($TxtHotSwapMinute.Text.Trim(), [ref]$swapMin) -or $swapMin -lt 5 -or $swapMin -gt 59) {
        Show-SettingsNotice "Hot-Swap Interval must be between 5 and 59 minutes." "Error"
        return
    }

    $priorityVal = 0
    if (-not [int]::TryParse($TxtPriority.Text.Trim(), [ref]$priorityVal) -or $priorityVal -lt 0 -or $priorityVal -gt 65535) {
        Show-SettingsNotice "SRV Priority must be an integer between 0 and 65535." "Error"
        return
    }

    $weightVal = 5
    if (-not [int]::TryParse($TxtWeight.Text.Trim(), [ref]$weightVal) -or $weightVal -lt 0 -or $weightVal -gt 65535) {
        Show-SettingsNotice "SRV Weight must be an integer between 0 and 65535." "Error"
        return
    }

    $ttlVal = 0
    if (-not [int]::TryParse($TxtTTL.Text.Trim(), [ref]$ttlVal) -or $ttlVal -lt 1) {
        Show-SettingsNotice "DNS TTL must be a positive number of seconds (e.g. 60)." "Error"
        return
    }

    $retentionVal = 0
    if (-not [int]::TryParse($TxtLogRetention.Text.Trim(), [ref]$retentionVal) -or $retentionVal -lt 1) {
        Show-SettingsNotice "Log Retention must be at least 1 day." "Error"
        return
    }

    $newCfg = @{
        DnsProvider        = $p
        HostingerToken     = $hToken
        CloudflareApiToken = $cToken
        CloudflareZoneId   = $TxtCloudflareZoneId.Text.Trim()
        RootDomain         = $domain
        SrvRecordName      = $srvName
        LocalPort          = [string]$port
        HotSwapMinute      = [string]$swapMin
        TTL                = [string]$ttlVal
        Priority           = [string]$priorityVal
        Weight             = [string]$weightVal
        LogRetentionDays   = [string]$retentionVal
    }

    Save-EnvSettings -cfg $newCfg
    $TxtPublicDomain.Text = Get-PlayerAddress -Srv $newCfg.SrvRecordName -Domain $newCfg.RootDomain

    if (Get-ServiceState) {
        Show-SettingsNotice "Settings saved! Restart Tunnel Gateway to apply new configuration." "Success"
    } else {
        Show-SettingsNotice "Settings saved to .env! (Provider: $p)" "Success"
    }
})

# Copy Server Address Button
$BtnCopyDomain.Add_Click({
    $currentAddr = $TxtPublicDomain.Text.Trim()
    if ([string]::IsNullOrWhiteSpace($currentAddr) -or $currentAddr -like "*Configure domain*" -or $currentAddr -like "*<Domain*") {
        Show-SettingsNotice "Please configure your domain in Settings first." "Error"
        Set-ActiveTab "Settings"
        return
    }
    [System.Windows.Clipboard]::SetText($currentAddr)
    $BtnCopyDomain.Content = "Copied!"
    $BtnCopyDomain.Background = "#059669"
    $t = New-Object System.Windows.Threading.DispatcherTimer
    $t.Interval = [TimeSpan]::FromSeconds(2)
    $t.Add_Tick({
        $BtnCopyDomain.Content = "Copy Server Address"
        $BtnCopyDomain.Background = "#0284C7"
        $t.Stop()
    })
    $t.Start()
})

# ------------------------------------------------------------
# LOG VIEWER HELPERS
# ------------------------------------------------------------
$BtnClearLogView.Add_Click({
    $TxtFullLogs.Text = ""
    $TxtDashboardLogs.Text = ""
})

$BtnOpenLogFile.Add_Click({
    $logFile = Get-CurrentLogFile
    if (Test-Path $logFile) {
        Start-Process notepad.exe -ArgumentList "`"$logFile`""
    } else {
        [System.Windows.MessageBox]::Show("Log file for today does not exist yet.", "TunnelKeeper", "OK", "Information")
    }
})

$BtnOpenLogFolder.Add_Click({
    if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }
    Start-Process explorer.exe -ArgumentList "`"$LogDir`""
})

# ------------------------------------------------------------
# SERVICE CONTROL (START / STOP / RESTART)
# ------------------------------------------------------------
function Get-ServiceState {
    $schedTask = Get-ScheduledTask -TaskName "Minecraft Tunnel Keeper" -ErrorAction SilentlyContinue
    $taskRunning = ($schedTask -and $schedTask.State -eq "Running")

    $mutexLocked = $false
    try {
        $testMutex = [System.Threading.Mutex]::OpenExisting("Global\TunnelKeeper_Gateway")
        $testMutex.Dispose()
        $mutexLocked = $true
    } catch [System.Threading.WaitHandleCannotBeOpenedException] {
        $mutexLocked = $false
    } catch {
        $mutexLocked = $true
    }

    $localPortText = $TxtLocalPort.Text.Trim()
    $sshProcs = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -eq "ssh.exe" -and ($_.CommandLine -match "a\.pinggy\.io" -or ($localPortText -and $_.CommandLine -match $localPortText))
    }

    $gwProcs = Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -like "powershell*.exe" -and $_.CommandLine -match "minecraft-tunnel-autostart\.ps1"
    }

    return ($taskRunning -or $mutexLocked -or (@($sshProcs).Count -gt 0) -or (@($gwProcs).Count -gt 0))
}

function Start-GatewayService {
    # Check domain configuration before launch
    $domain = $TxtRootDomain.Text.Trim()
    if ([string]::IsNullOrWhiteSpace($domain) -or $domain -in @("yourdomain.com", "example.com")) {
        [System.Windows.MessageBox]::Show("Please enter your own registered domain name in the Settings tab before starting the tunnel gateway.", "Domain Configuration Required", [System.Windows.MessageBoxButton]::OK, [System.Windows.MessageBoxImage]::Warning)
        Set-ActiveTab "Settings"
        return
    }

    # Check provider token
    $p = if ($RadioCloudflare.IsChecked) { "Cloudflare" } else { "Hostinger" }
    $hToken = if ($TxtHostingerTokenVisible.Visibility -eq "Visible") { $TxtHostingerTokenVisible.Text.Trim() } else { $TxtHostingerToken.Password.Trim() }
    $cToken = if ($TxtCloudflareTokenVisible.Visibility -eq "Visible") { $TxtCloudflareTokenVisible.Text.Trim() } else { $TxtCloudflareToken.Password.Trim() }
    if ($p -eq "Hostinger" -and [string]::IsNullOrWhiteSpace($hToken)) {
        [System.Windows.MessageBox]::Show("Please enter your Hostinger API Token in the Settings tab before starting.", "API Token Required", [System.Windows.MessageBoxButton]::OK, [System.Windows.MessageBoxImage]::Warning)
        Set-ActiveTab "Settings"
        return
    }
    if ($p -eq "Cloudflare" -and [string]::IsNullOrWhiteSpace($cToken)) {
        [System.Windows.MessageBox]::Show("Please enter your Cloudflare API Token in the Settings tab before starting.", "API Token Required", [System.Windows.MessageBoxButton]::OK, [System.Windows.MessageBoxImage]::Warning)
        Set-ActiveTab "Settings"
        return
    }

    $BtnToggleService.IsEnabled = $false
    $BtnToggleService.Content   = "Starting..."
    $BtnToggleService.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#D97706")

    # Launch daemon in hidden background process
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName         = "powershell.exe"
    $psi.Arguments        = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$CoreScriptPath`" -Force"
    $psi.WorkingDirectory = $ScriptRoot
    $psi.CreateNoWindow   = $true
    $psi.UseShellExecute  = $false
    [System.Diagnostics.Process]::Start($psi) | Out-Null
}

function Stop-GatewayService {
    $BtnToggleService.IsEnabled = $false
    $BtnToggleService.Content   = "Stopping..."
    $BtnToggleService.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#D97706")

    # Stop scheduled task if present
    Stop-ScheduledTask -TaskName "Minecraft Tunnel Keeper" -ErrorAction SilentlyContinue

    # Kill Pinggy SSH processes
    $localPortText = $TxtLocalPort.Text.Trim()
    Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -eq "ssh.exe" -and ($_.CommandLine -match "a\.pinggy\.io" -or ($localPortText -and $_.CommandLine -match $localPortText))
    } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }

    # Terminate background powershell running the core script
    Get-CimInstance Win32_Process -ErrorAction SilentlyContinue | Where-Object {
        $_.Name -like "powershell*.exe" -and $_.CommandLine -match "minecraft-tunnel-autostart\.ps1"
    } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

$BtnToggleService.Add_Click({
    $isRunning = Get-ServiceState
    if ($isRunning) {
        Stop-GatewayService
    } else {
        Start-GatewayService
    }
})

$BtnRestartService.Add_Click({
    Stop-GatewayService
    Start-Sleep -Seconds 2
    Start-GatewayService
})

# ------------------------------------------------------------
# SYSTEM TRAY INTEGRATION
# ------------------------------------------------------------
$script:IsExplicitExit = $false

$notifyIcon = New-Object System.Windows.Forms.NotifyIcon
if (Test-Path $IconFilePath) {
    $notifyIcon.Icon = New-Object System.Drawing.Icon($IconFilePath)
} else {
    $notifyIcon.Icon = [System.Drawing.SystemIcons]::Application
}
$notifyIcon.Text = "TunnelKeeper - Minecraft Gateway"
$notifyIcon.Visible = $true

$contextMenu = New-Object System.Windows.Forms.ContextMenuStrip
$itemOpen = $contextMenu.Items.Add("Open Dashboard")
$itemOpen.Add_Click({
    $window.Show()
    $window.WindowState = "Normal"
    $window.Activate()
})
$itemSep = $contextMenu.Items.Add("-")
$itemStart = $contextMenu.Items.Add("Start Tunnel")
$itemStart.Add_Click({ Start-GatewayService })
$itemStop = $contextMenu.Items.Add("Stop Tunnel")
$itemStop.Add_Click({ Stop-GatewayService })
$itemSep2 = $contextMenu.Items.Add("-")
$itemExit = $contextMenu.Items.Add("Exit TunnelKeeper")
$itemExit.Add_Click({
    $script:IsExplicitExit = $true
    $refreshTimer.Stop()
    $notifyIcon.Visible = $false
    $notifyIcon.Dispose()
    $window.Close()
    $app.Shutdown()
})
$notifyIcon.ContextMenuStrip = $contextMenu

$notifyIcon.Add_DoubleClick({
    $window.Show()
    $window.WindowState = "Normal"
    $window.Activate()
})

$BtnMinimizeTray.Add_Click({
    $window.Hide()
    $notifyIcon.ShowBalloonTip(2000, "TunnelKeeper", "Running in background. Double-click icon to reopen.", [System.Windows.Forms.ToolTipIcon]::Info)
})

# ------------------------------------------------------------
# REFRESH TIMER (Updates status, checks server, streams logs)
# ------------------------------------------------------------
$lastLogFileContent = ""
$lastLogCheck = [DateTime]::MinValue
$lastDnsCheck = [DateTime]::MinValue

$refreshTimer = New-Object System.Windows.Threading.DispatcherTimer
$refreshTimer.Interval = [TimeSpan]::FromSeconds(1)

$refreshTimer.Add_Tick({
    $isRunning = Get-ServiceState

    # Update Service Status Badge & Buttons
    if ($isRunning) {
        $BadgeStatus.Background    = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#064E3B")
        $TxtBadgeStatus.Text       = "ONLINE"
        $TxtBadgeStatus.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#34D399")
        $BtnToggleService.Content  = "Stop Tunnel Gateway"
        $BtnToggleService.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#DC2626")
        $BtnToggleService.IsEnabled  = $true
    } else {
        $BadgeStatus.Background    = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#450A0A")
        $TxtBadgeStatus.Text       = "STOPPED"
        $TxtBadgeStatus.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#F87171")
        $BtnToggleService.Content  = "Start Tunnel Gateway"
        $BtnToggleService.Background = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#059669")
        $BtnToggleService.IsEnabled  = $true
    }

    $currProv = if ($RadioCloudflare.IsChecked) { "Cloudflare" } else { "Hostinger" }
    $TxtProviderLabel.Text = "Provider: $currProv"

    # Check local Minecraft server port (every 5 seconds)
    if (((Get-Date) - $lastLogCheck).TotalSeconds -ge 5) {
        $lastLogCheck = Get-Date
        $portNum = 25565
        [int]::TryParse($TxtLocalPort.Text, [ref]$portNum) | Out-Null
        $client = New-Object System.Net.Sockets.TcpClient
        try {
            $iar = $client.BeginConnect("127.0.0.1", $portNum, $null, $null)
            $ok = $iar.AsyncWaitHandle.WaitOne(100, $false)
            if ($ok -and $client.Connected) {
                $TxtLocalServerLabel.Text = "Minecraft: Online (Port $portNum)"
                $TxtLocalServerLabel.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#34D399")
            } else {
                $TxtLocalServerLabel.Text = "Minecraft: Idle (Port $portNum)"
                $TxtLocalServerLabel.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#94A3B8")
            }
        } catch {
            $TxtLocalServerLabel.Text = "Minecraft: Idle"
        } finally {
            $client.Close()
            $client.Dispose()
        }
    }

    # Query public SRV record (every 15 seconds)
    if (((Get-Date) - $lastDnsCheck).TotalSeconds -ge 15) {
        $lastDnsCheck = Get-Date
        try {
            $dom = $TxtRootDomain.Text.Trim()
            if (-not [string]::IsNullOrWhiteSpace($dom) -and $dom -notin @("yourdomain.com", "example.com")) {
                $fullSrv = "$($TxtSrvRecordName.Text).$dom"
                $recs = Resolve-DnsName -Name $fullSrv -Type SRV -ErrorAction SilentlyContinue
                if ($recs -and $recs.Count -gt 0) {
                    $tgt = ("" + $recs[0].Target).TrimEnd('.')
                    $prt = $recs[0].Port
                    $TxtLiveEndpoint.Text = "SRV: ${tgt}:${prt}"
                    $TxtLiveEndpoint.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#34D399")
                } else {
                    $TxtLiveEndpoint.Text = "SRV: Record propagating..."
                    $TxtLiveEndpoint.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#94A3B8")
                }
            } else {
                $TxtLiveEndpoint.Text = "SRV: Setup domain in Settings"
                $TxtLiveEndpoint.Foreground = [System.Windows.Media.BrushConverter]::new().ConvertFromString("#94A3B8")
            }
        } catch {}
    }

    # Read latest log file
    $logPath = Get-CurrentLogFile
    $TxtLogFileSummary.Text = Split-Path -Leaf $logPath
    $TxtFullLogPath.Text    = $logPath

    if (Test-Path $logPath) {
        $fs = $null
        $sr = $null
        try {
            # Read non-locked stream
            $fs = [System.IO.FileStream]::new($logPath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            $sr = [System.IO.StreamReader]::new($fs, [System.Text.Encoding]::UTF8)
            $logContent = $sr.ReadToEnd()

            if ($logContent -ne $lastLogFileContent) {
                $lastLogFileContent = $logContent

                # Dashboard mini console (last 12 lines)
                $lines = $logContent -split "`r?`n" | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }
                $tailCount = [math]::Min(12, $lines.Count)
                if ($tailCount -gt 0) {
                    $recent = ($lines[($lines.Count - $tailCount)..($lines.Count - 1)]) -join "`r`n"
                    $TxtDashboardLogs.Text = $recent
                    $TxtDashboardLogs.ScrollToEnd()
                }

                # Full logs tab
                $TxtFullLogs.Text = $logContent
                if ($ChkAutoScroll.IsChecked) {
                    $TxtFullLogs.ScrollToEnd()
                }

                # Parse hot swap stats from logs
                $swapMatch = [regex]::Matches($logContent, 'Swap #(\d+)')
                if ($swapMatch.Count -gt 0) {
                    $TxtCycleCount.Text = "Swaps: $($swapMatch[$swapMatch.Count - 1].Groups[1].Value) completed"
                }
                $uptimeMatch = [regex]::Matches($logContent, 'Uptime: ([0-9dhms ]+)')
                if ($uptimeMatch.Count -gt 0) {
                    $TxtUptime.Text = "Uptime: " + $uptimeMatch[$uptimeMatch.Count - 1].Groups[1].Value.Trim()
                }
            }
        } catch {
        } finally {
            if ($sr) { $sr.Dispose() }
            if ($fs) { $fs.Dispose() }
        }
    }
})

$refreshTimer.Start()

# Window close handler: intercept X to keep tunnel running in tray
$window.Add_Closing({
    param($sender, $e)
    if (-not $script:IsExplicitExit) {
        $e.Cancel = $true
        $window.Hide()
        $notifyIcon.ShowBalloonTip(2000, "TunnelKeeper", "Minimized to tray. Double-click icon to reopen.", [System.Windows.Forms.ToolTipIcon]::Info)
    }
})

# Show UI and run application loop
$window.Show()
$app.Run() | Out-Null
