<#
====================================================================
 TunnelKeeper - Core Configuration Module
 Handles .env parsing, default value assignment, and persistence
====================================================================
#>

function Find-EnvFile {
    param([string]$StartDir = $PSScriptRoot)
    
    $candidates = @(
        (Join-Path $StartDir ".env"),
        (Join-Path (Split-Path -Parent $StartDir) ".env"),
        (Join-Path (Split-Path -Parent (Split-Path -Parent $StartDir)) ".env")
    )
    
    foreach ($path in $candidates) {
        if (Test-Path $path) {
            return (Resolve-Path $path).Path
        }
    }
    
    # Fallback to current working location
    $cwdEnv = Join-Path (Get-Location).Path ".env"
    if (Test-Path $cwdEnv) {
        return (Resolve-Path $cwdEnv).Path
    }
    
    return $null
}

function Get-TunnelKeeperConfig {
    param([string]$EnvPath)

    if (-not $EnvPath -or -not (Test-Path $EnvPath)) {
        $EnvPath = Find-EnvFile
    }

    $cfg = @{
        DnsProvider        = "Hostinger"
        HostingerToken     = ""
        CloudflareApiToken = ""
        CloudflareZoneId   = ""
        RootDomain         = ""
        SrvRecordName      = "_minecraft._tcp.play"
        LocalPort          = 25565
        Priority           = 0
        Weight             = 5
        TTL                = 60
        HotSwapMinute      = 55
        LogRetentionDays   = 14
        _EnvPath           = $EnvPath
    }

    if ($EnvPath -and (Test-Path $EnvPath)) {
        foreach ($line in Get-Content $EnvPath) {
            $trimmed = $line.Trim()
            if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) { continue }
            if ($trimmed -match '^([^=]+)=(.*)$') {
                $k = $matches[1].Trim()
                $v = $matches[2].Trim()
                if ($v -match '^["''](.*)["'']$') { $v = $matches[1] }
                switch ($k) {
                    "DnsProvider"        { $cfg["DnsProvider"]        = $v }
                    "HostingerToken"     { $cfg["HostingerToken"]     = $v }
                    "CloudflareApiToken" { $cfg["CloudflareApiToken"] = $v }
                    "CloudflareToken"    { $cfg["CloudflareApiToken"] = $v }
                    "CloudflareZoneId"   { $cfg["CloudflareZoneId"]   = $v }
                    "RootDomain"         { $cfg["RootDomain"]         = $v }
                    "SrvRecordName"      { $cfg["SrvRecordName"]      = $v }
                    "LocalPort"          { $parsed = 0; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["LocalPort"] = $parsed } }
                    "Priority"           { $parsed = 0; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["Priority"] = $parsed } }
                    "Weight"             { $parsed = 5; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["Weight"] = $parsed } }
                    "TTL"                { $parsed = 60; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["TTL"] = $parsed } }
                    "HotSwapMinute"      { $parsed = 55; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["HotSwapMinute"] = $parsed } }
                    "LogRetentionDays"   { $parsed = 14; if ([int]::TryParse($v, [ref]$parsed)) { $cfg["LogRetentionDays"] = $parsed } }
                }
            }
        }
    }

    # Auto-detect provider if default
    if ([string]::IsNullOrWhiteSpace($cfg["DnsProvider"]) -or $cfg["DnsProvider"] -eq "Hostinger") {
        if ([string]::IsNullOrEmpty($cfg["HostingerToken"]) -and -not [string]::IsNullOrEmpty($cfg["CloudflareApiToken"])) {
            $cfg["DnsProvider"] = "Cloudflare"
        } else {
            $cfg["DnsProvider"] = "Hostinger"
        }
    }

    return $cfg
}

function Save-TunnelKeeperConfig {
    param(
        [hashtable]$Config,
        [string]$EnvPath
    )

    if (-not $EnvPath) {
        $EnvPath = $Config["_EnvPath"]
    }
    if (-not $EnvPath) {
        $EnvPath = Join-Path (Get-Location).Path ".env"
    }

    $lines = @(
        "# ============================================================",
        "# TunnelKeeper Gateway - Configuration File",
        "# Auto-generated by TunnelKeeper Dashboard",
        "# ============================================================",
        "",
        "DnsProvider=$($Config['DnsProvider'])",
        "HostingerToken=$($Config['HostingerToken'])",
        "CloudflareApiToken=$($Config['CloudflareApiToken'])",
        "CloudflareZoneId=$($Config['CloudflareZoneId'])",
        "RootDomain=$($Config['RootDomain'])",
        "SrvRecordName=$($Config['SrvRecordName'])",
        "LocalPort=$($Config['LocalPort'])",
        "Priority=$($Config['Priority'])",
        "Weight=$($Config['Weight'])",
        "TTL=$($Config['TTL'])",
        "HotSwapMinute=$($Config['HotSwapMinute'])",
        "LogRetentionDays=$($Config['LogRetentionDays'])"
    )

    $lines -join "`r`n" | Out-File -FilePath $EnvPath -Encoding utf8
}

function Get-PlayerAddress {
    param(
        [string]$Srv,
        [string]$Domain
    )

    if ([string]::IsNullOrWhiteSpace($Domain) -or $Domain -in @("yourdomain.com", "example.com")) {
        return "Configure domain in Settings"
    }
    if ($Srv -match '^_[^.]+\._[^.]+\.(.+)$') {
        $sub = $matches[1].TrimEnd('.')
        if (-not [string]::IsNullOrWhiteSpace($sub)) {
            return "$sub.$Domain"
        }
    }
    return $Domain
}

function Test-TunnelKeeperConfig {
    param([hashtable]$Config)

    $results = @{
        IsValid = $true
        Errors  = [System.Collections.Generic.List[string]]::new()
        Warnings = [System.Collections.Generic.List[string]]::new()
    }

    if ([string]::IsNullOrWhiteSpace($Config["RootDomain"]) -or $Config["RootDomain"] -in @("yourdomain.com", "example.com")) {
        $results.IsValid = $false
        $results.Errors.Add("RootDomain is not configured. Please enter your domain name.")
    }

    if ($Config["DnsProvider"] -eq "Cloudflare") {
        if ([string]::IsNullOrWhiteSpace($Config["CloudflareApiToken"]) -or $Config["CloudflareApiToken"] -eq "YOUR_CLOUDFLARE_API_TOKEN_HERE") {
            $results.IsValid = $false
            $results.Errors.Add("CloudflareApiToken is required when using Cloudflare DNS.")
        }
    } else {
        if ([string]::IsNullOrWhiteSpace($Config["HostingerToken"]) -or $Config["HostingerToken"] -eq "YOUR_HOSTINGER_API_TOKEN_HERE") {
            $results.IsValid = $false
            $results.Errors.Add("HostingerToken is required when using Hostinger DNS.")
        }
    }

    return $results
}
